change template
Signed-off-by: oliver könig <okoenig@nvidia.com>

diff --git a/nemo_run/core/execution/templates/ft_launcher_dgxc.j2 b/nemo_run/core/execution/templates/ft_launcher_dgxc.j2
--- a/nemo_run/core/execution/templates/ft_launcher_dgxc.j2
+++ b/nemo_run/core/execution/templates/ft_launcher_dgxc.j2
@@ -1,50 +1,46 @@
 {% macro ft_launcher_setup(fault_tol_cfg_path, fault_tol_finished_flag_file, fault_tol_job_results_file) -%}
-
+# This script uses experimental fault tolerance launcher
+# Fault tolerance related items
 export FAULT_TOL_CFG_PATH="{{fault_tol_cfg_path}}"
 export FAULT_TOL_FINISHED_FLAG_FILE="{{fault_tol_finished_flag_file}}"
-export FAULT_TOL_JOB_RESULTS_FILE="{{fault_tol_job_results_file}}"
+ANY_JOB_STEP_FAILED=0
 
-is_training_finished() {
-    test -f "$FAULT_TOL_FINISHED_FLAG_FILE"
+# Automatic job resubmission related items
+JOB_RESULTS_FILE="{{fault_tol_job_results_file}}"
+is_job_failures_limit_reached() {
+    if [ $TORCHX_MAX_RETRIES -eq 0 ]; then
+       true
+    else
+        tail -n $TORCHX_MAX_RETRIES "$JOB_RESULTS_FILE" | \
+            awk "/^[[:alnum:]]+[[:space:]]+[[:alnum:]]+[[:space:]]+[XF]$/{f++} END{exit !(f>=$TORCHX_MAX_RETRIES)}"
+    fi
 }
-
-if is_training_finished ; then
-    echo "[FT-Setup] Found finished flag at $FAULT_TOL_FINISHED_FLAG_FILE."
-    echo "[FT-Setup] Training is already complete. Exiting successfully."
-    exit 0
+is_training_finished() {
+    test -f "$(dirname $JOB_RESULTS_FILE)/$(basename $FAULT_TOL_FINISHED_FLAG_FILE)"
+}
+# Exit immediately if finished flag file exists and this job is a continuation
+if [ -v RETRY_COUNT ] && [ "$RETRY_COUNT" -gt 0 ] ; then
+    if is_training_finished ; then echo "Training is finished" ; exit 0 ; fi
+    if is_job_failures_limit_reached ; then echo "Job failures limit reached ($TORCHX_MAX_RETRIES)" ; exit 1 ; fi
+else
+    rm -f "$FAULT_TOL_FINISHED_FLAG_FILE" "$JOB_RESULTS_FILE"
 fi
 
-echo "[FT-Setup] Starting training on $(hostname)..."
-if [ -n "$FAULT_TOL_JOB_RESULTS_FILE" ]; then
-    mkdir -p "$(dirname "$FAULT_TOL_JOB_RESULTS_FILE")"
-    echo "$(hostname) $(date +%s) X" >> "$FAULT_TOL_JOB_RESULTS_FILE"
-fi
-
+# Write unknown job status to the job log, we will fix it at the end
+echo "$TORCHX_REPLICA_ID ${RETRY_COUNT:-0} X" >> "$JOB_RESULTS_FILE"
 {%- endmacro %}
 
 {% macro ft_launcher_teardown() -%}
-if [ "$exitcode" -eq "0" ]; then
-    RESULT_STATUS="S" # Success
+if [ $exitcode -ne 0 ]; then ANY_JOB_STEP_FAILED=1 ; fi
+# Fix the job log entry ("JOB_ID X" -> "JOB_ID S/F"), depending on the job result
+if [ "$ANY_JOB_STEP_FAILED" = "0" ] ; then
+   sed -i "s/$TORCHX_REPLICA_ID ${RETRY_COUNT:-0} X/$TORCHX_REPLICA_ID ${RETRY_COUNT:-0} S/" "$JOB_RESULTS_FILE"
 else
-    RESULT_STATUS="F" # Failure
+   sed -i "s/$TORCHX_REPLICA_ID ${RETRY_COUNT:-0} X/$TORCHX_REPLICA_ID ${RETRY_COUNT:-0} F/" "$JOB_RESULTS_FILE"
 fi
 
-if [ -n "$FAULT_TOL_JOB_RESULTS_FILE" ]; then
-    mkdir -p "$(dirname "$FAULT_TOL_JOB_RESULTS_FILE")"
-    echo "$(hostname) $(date +%s) $RESULT_STATUS" >> "$FAULT_TOL_JOB_RESULTS_FILE"
-fi
-
-if [ "$exitcode" -eq "0" ]; then
-    if is_training_finished; then
-        echo "[FT-Teardown] Job finished successfully and flag file exists."
-        exit 0
-    else
-        echo "[FT-Teardown] WARNING: Process exited 0 but finished flag is MISSING."
-        echo "[FT-Teardown] Forcing exit 1 to trigger Kubernetes restart."
-        exit 1
-    fi
-else
-    echo "[FT-Teardown] Job failed with exit code $exitcode."
+if ! (is_training_finished || is_job_failures_limit_reached); then
+    scontrol requeue "$TORCHX_REPLICA_ID"
     exit $exitcode
 fi
 {%- endmacro %}
